[connections.snowflake]
connection_name = "snowflake"

[connections.snowflake]
account = "xxxxxxx-xxxxxxx"
user = "Chenna"
role = "SYSADMIN"
warehouse = "CMPUTE_WH"
database = "SMOOTIES"
schema = "PUBLIC"
